---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab2rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab2rbac:authenticated
rules:
- apiGroups: ["*"]
  resources:
    - apiservices
    - componentstatuses
    - namespaces
    - nodes
  verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # NOTE: don't change the prefix gitlab2rbac:
  name: gitlab2rbac:guest
rules:
- apiGroups: ["*"]
  resources:
  # workload
  - cronjobs
  - daemonsets
  - deployments
  - horizontalpodautoscalers
  - ingresses
  - jobs
  - pods
  - replicasets
  - replicationcontrollers
  - services
  - statefulsets
  # setup
  - configmaps
  - endpoints
  - networkpolicies
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - serviceaccounts
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab2rbac:reporter
rules:
- apiGroups: ["*"]
  resources:
  # actions
  - pods/log
  - pods/portforward
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["*"]
  resources:
  # workload
  - cronjobs
  - daemonsets
  - deployments
  - events
  - horizontalpodautoscalers
  - ingresses
  - jobs
  - pods
  - replicasets
  - replicationcontrollers
  - services
  - statefulsets
  # setup
  - configmaps
  - endpoints
  - networkpolicies
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - serviceaccounts
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab2rbac:developer
rules:
- apiGroups: ["*"]
  resources:
  # workload
  - cronjobs
  - daemonsets
  - deployments
  - deployments/scale
  - horizontalpodautoscalers
  - ingresses
  - jobs
  - pods
  - replicasets
  - replicationcontrollers
  - services
  - statefulsets
  # actions
  - deployments/rollback
  - deployments/scale
  - pods/attach
  - pods/exec
  - pods/log
  - pods/portforward
  - replicasets/scale
  - replicationcontrollers/scale
  - statefulsets/scale
  # setup
  - certificates
  - configmaps
  - endpoints
  - networkpolicies
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["*"]
  resources:
  # workload
  - events
  # setup
  - limitranges
  - resourcequotas
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab2rbac:maintainer
rules:
- apiGroups: ["*"]
  resources:
  # workload
  - cronjobs
  - daemonsets
  - deployments
  - deployments/scale
  - events
  - horizontalpodautoscalers
  - ingresses
  - jobs
  - pods
  - replicasets
  - replicationcontrollers
  - services
  - statefulsets
  # actions
  - deployments/rollback
  - deployments/scale
  - pods/attach
  - pods/exec
  - pods/log
  - pods/portforward
  - replicasets/scale
  - replicationcontrollers/scale
  - statefulsets/scale
  # setup
  - certificates
  - configmaps
  - endpoints
  - limitranges
  - networkpolicies
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - resourcequotas
  - rolebindings
  - roles
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab2rbac:admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
- nonResourceURLs: ['*']
  verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab2rbac:authenticated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab2rbac:authenticated
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab2rbac:guest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab2rbac:guest
subjects:
- kind: ServiceAccount
  name: gitlab2rbac
  namespace: gitlab2rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab2rbac:reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab2rbac:reporter
subjects:
- kind: ServiceAccount
  name: gitlab2rbac
  namespace: gitlab2rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab2rbac:developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab2rbac:developer
subjects:
- kind: ServiceAccount
  name: gitlab2rbac
  namespace: gitlab2rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab2rbac:maintainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab2rbac:maintainer
subjects:
- kind: ServiceAccount
  name: gitlab2rbac
  namespace: gitlab2rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab2rbac:admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab2rbac:admin
subjects:
- kind: ServiceAccount
  name: gitlab2rbac
  namespace: gitlab2rbac
